#!/usr/bin/env bash
#
# codex-setup.sh - make this resume workspace work in OpenAI Codex CLI.
#
# Claude Code reads .claude/skills/ for /start, /jobupdate, and the rest.
# Codex does not. It reads two different things:
#
#   1. AGENTS.md at the repo root  - its steering file (like CLAUDE.md).
#   2. $CODEX_HOME/prompts/*.md     - custom prompts. Each name.md becomes /name.
#
# This script generates both from the files already in this workspace, so you
# get the same /start, /jobupdate, /atscheck, /build, /humanizer commands in
# Codex that you have in Claude Code. Re-running it is safe (it overwrites the
# files it owns and backs up anything of yours it would replace).
#
# Usage:
#   bash codex-setup.sh            # install prompts to ~/.codex/prompts
#   bash codex-setup.sh --local    # install to ./.codex/prompts (project-scoped)
#   bash codex-setup.sh --uninstall
#
set -euo pipefail

# Workspace root = where this script lives.
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILLS_DIR="$ROOT/.claude/skills"
SKILLS=(start jobupdate atscheck build humanizer)

MODE="install"
LOCAL=0
for arg in "$@"; do
  case "$arg" in
    --local) LOCAL=1 ;;
    --uninstall) MODE="uninstall" ;;
    -h|--help)
      sed -n '2,30p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'
      exit 0 ;;
    *) echo "Unknown option: $arg (try --help)"; exit 1 ;;
  esac
done

# Where Codex looks for custom prompts.
if [ "$LOCAL" -eq 1 ]; then
  CODEX_HOME_DIR="$ROOT/.codex"
else
  CODEX_HOME_DIR="${CODEX_HOME:-$HOME/.codex}"
fi
PROMPTS_DIR="$CODEX_HOME_DIR/prompts"

# --- uninstall ---------------------------------------------------------------
if [ "$MODE" = "uninstall" ]; then
  echo "Removing Codex prompts from $PROMPTS_DIR"
  for name in "${SKILLS[@]}"; do
    rm -f "$PROMPTS_DIR/$name.md"
  done
  echo "Left AGENTS.md in place (delete it by hand if you want it gone)."
  echo "Done."
  exit 0
fi

# --- 1. AGENTS.md ------------------------------------------------------------
# Codex auto-loads AGENTS.md from the repo root. Rather than duplicate the rules
# (which would drift), point it at CLAUDE.md, which stays the single source.
AGENTS="$ROOT/AGENTS.md"
if [ -f "$AGENTS" ] && ! grep -q "GENERATED BY codex-setup.sh" "$AGENTS" 2>/dev/null; then
  cp "$AGENTS" "$AGENTS.bak"
  echo "Backed up your existing AGENTS.md to AGENTS.md.bak"
fi
cat > "$AGENTS" <<'EOF'
<!-- GENERATED BY codex-setup.sh - edit CLAUDE.md instead, then re-run the script. -->

# Resume workspace (Codex)

This is a resume-building workspace. The full house rules live in `CLAUDE.md`:
writing style, the always-on humanizer pass, the ATS rules, and the hard rules
(never invent experience, skills, projects, or numbers).

Read `CLAUDE.md` now and follow it exactly. Everything in it applies to you,
the same as it does to Claude Code. Where it says "CLAUDE.md", read "this
workspace's rules" - the file is right there in the root.

The commands `/start`, `/jobupdate`, `/atscheck`, `/build`, and `/humanizer`
are installed as Codex prompts. Run Codex from this folder so the relative
paths in those prompts resolve.
EOF
echo "Wrote $AGENTS"

# --- 2. Convert each skill into a Codex prompt -------------------------------
mkdir -p "$PROMPTS_DIR"
for name in "${SKILLS[@]}"; do
  src="$SKILLS_DIR/$name/SKILL.md"
  dest="$PROMPTS_DIR/$name.md"
  if [ ! -f "$src" ]; then
    echo "Skipping $name - $src not found"
    continue
  fi
  # Back up a pre-existing prompt of the same name that we didn't write.
  if [ -f "$dest" ] && ! grep -q "GENERATED BY codex-setup.sh" "$dest" 2>/dev/null; then
    cp "$dest" "$dest.bak"
    echo "Backed up existing $dest to $dest.bak"
  fi

  # Strip the YAML frontmatter (everything between the first pair of --- lines),
  # then prepend a short header so Codex loads the workspace rules first.
  {
    cat <<EOF
<!-- GENERATED BY codex-setup.sh from .claude/skills/$name/SKILL.md - edit the skill, then re-run. -->

You are running inside a resume-building workspace. Before anything else, read
AGENTS.md and CLAUDE.md in the workspace root and follow every rule in them
exactly. All paths below are relative to the workspace root, so run Codex from
this folder.

EOF
    awk '
      NR==1 && $0=="---" {fm=1; next}
      fm==1 && $0=="---" {fm=2; next}
      fm!=1 {print}
    ' "$src"
  } > "$dest"
  echo "Wrote $dest  (use /$name in Codex)"
done

echo
echo "Done. In Codex:"
echo "  cd \"$ROOT\""
echo "  codex"
echo "  then type /start, /jobupdate, /atscheck, /build, or /humanizer"
if [ "$LOCAL" -eq 1 ]; then
  echo
  echo "You installed --local. Point Codex at this folder's prompts with:"
  echo "  export CODEX_HOME=\"$CODEX_HOME_DIR\""
  echo "(add that line to your shell profile to make it stick)."
fi
